#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    miniGoalPot,    sensorPotentiometer)
#pragma config(Sensor, in5,    lightLeft,      sensorReflection)
#pragma config(Sensor, in6,    lightRight,     sensorReflection)
#pragma config(Sensor, in7,    lightMid,       sensorReflection)
#pragma config(Sensor, dgtl1,  encArm,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  handsDown,      sensorTouch)
#pragma config(Sensor, dgtl6,  handsUp,        sensorTouch)
#pragma config(Sensor, dgtl8,  urfOut,         sensorSONAR_inch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           pushGoalHand,  tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           frontLeftDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontRightDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           goalHands,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           coneArms,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           backBackLeftDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           backLeftDrive, tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port8,           backBackRightDrive, tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port9,           backRightDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          claw,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//warning code is slightly agressive.

/*Compo Init*/
#pragma platform(VEX);

#pragma competitionControl(Competition);
#pragma autonomousDuration(9000);
#pragma userControlDuration(9000);

#include "Vex_Competition_Includes.c" //backcode no modify pls.

/*Other Scripts*/
//#include "64008Z_auto_v2.c" //autonomous code.
const int down = 1;
const int up = 2;
const int mid = 3;
const int completed = 4;

const int dir_forwards = 1;
const int dir_backwards = -1;
const int dir_left = -1;
const int dir_right = 1;

const float mod_degrees = (278 / 360) * 10;  //multiply this with degrees to get
const float mod_wheel_circumference = 4 * 3.1415926535897932; //in inches.  (that's right, I memorized that many characters...)

bool inTeleop = false;

///initialize the gyroscope
void gyroInit() {
	//writeDebugStreamLine("Gyro Reset.");
	SensorType[gyro] = sensorNone;
	wait1Msec(1000);

	//writeDebugStreamLine("Gyro Assign..");
	SensorType[gyro] = sensorGyro;
	wait1Msec(2000);

	//writeDebugStreamLine("Gyro Setup...");
	//SensorScale[gyro] = 278;  //?
	SensorValue[gyro] = 0;
	SensorFullCount[gyro] = 3600;  //not working? gyro is auto set to 3600. dunno dont care.
}

//TODO: TEST THIS.
///direction = up(const) for up move and down(const) for down move.
int armParam = 0;
task autoMoveGoalArms() {
	if(armParam == up) {
		motor[goalHands] = 127;
    waitUntil(SensorValue[handsUp] == 1);
	}
	else if(armParam == down) {
		motor[goalHands] = -127;
    waitUntil(SensorValue[handsDown] == 1);
	}

  armParam = completed;

	motor[goalHands] = 0;
}

//TODO: TEST THIS.
//sensorPotentiometer:
const int pot_up = 4095;
const int pot_down = 1905;
const int pot_no_ground = 2150;

//not super accurate (doesn't need to be.)
int miniArmParam = 0;
task autoMoveMiniGoalArms() {
	if(miniArmParam == up) {
		motor[pushGoalHand] = 127;
    waitUntil(SensorValue[miniGoalPot] >= pot_up);  //insert up pos here
	}
	else if(miniArmParam == down) {
		motor[pushGoalHand] = -127;
    waitUntil(SensorValue[miniGoalPot] <= pot_down);  //insert down pos here
	}
	else if (miniArmParam == mid) {
		if(SensorValue[miniGoalPot] < pot_no_ground) {
			motor[pushGoalHand] = 127;
			waitUntil(SensorValue[miniGoalPot] >= pot_no_ground);
		}
		else {
			motor[pushGoalHand] = -127;
			waitUntil(SensorValue[miniGoalPot] <= pot_no_ground);
		}
	}

  miniArmParam = completed;

	motor[pushGoalHand] = 0;
}

float kp = 2;  //Tune?

float errorVal = 0;

float leftMod = 0;
float rightMod = 0;
void straightenMotors() {
  //set offset value, if 0 both sides are moving at same speed.  use abs value for both motors, pretending both sides going forwards.
  errorVal = (abs(nMotorEncoder[backLeftDrive]) - abs(nMotorEncoder[backRightDrive]));

  //update both modifiers.
  rightMod = (errorVal * kp);
  leftMod = -rightMod;

  writeDebugStreamLine("mod = error[%d] * kp[%d] = +[%d]", errorVal, kp, leftMod);  //DEBUG: this
  //writeDebugStreamLine("The error of (L - R) is %d degrees", errorVal);  //DEBUG: this
}

void resetMoveMod () { leftMod = 2; rightMod = -2; }  //small func.

//*VERY IMPORTANT*: THIS MUST BE CALLED FOR STRAIGHTENING TO OCCUR.
//sets the speed of the left and right sides of the drive.  Empty is not moving.
void setLeftRightMoveSpeed(int leftSpeed=0, int rightSpeed=0) {
  if (inTeleop == false) {
    straightenMotors();
  }  //make sure not to straighten motors while in teleop.  Don't fuck with Victor.

  //calculate deadzone.
  if(abs(leftSpeed) < 5) { leftSpeed = 0; }
  if(abs(rightSpeed) < 5) { rightSpeed = 0; }

	//left side, add positive mod (mod is scaled pased on speed).
	motor[frontLeftDrive] = abs(leftSpeed) + leftMod * (abs(leftSpeed)/127);
  motor[backLeftDrive] = abs(leftSpeed) + leftMod * (abs(leftSpeed)/127);
  motor[backBackLeftDrive] = abs(leftSpeed) + leftMod * (abs(leftSpeed)/127);
  //if negitave, make negitave.
  if(leftSpeed < 0) {
    motor[frontLeftDrive] *= -1;
    motor[backLeftDrive] *= -1;
    motor[backBackLeftDrive] *= -1;
  }

	//right side, add positive mod (mod is scaled based on speed).
	motor[frontRightDrive] = abs(rightSpeed) + rightMod * (abs(rightSpeed)/127);
	motor[backRightDrive] = abs(rightSpeed) + rightMod * (abs(rightSpeed)/127);
	motor[backBackRightDrive] = abs(rightSpeed) + rightMod * (abs(rightSpeed)/127);
  //if negitave, make negitave.
  if(rightSpeed < 0) {
    motor[frontRightDrive] *= -1;
    motor[backRightDrive] *= -1;
    motor[backBackRightDrive] *= -1;
  }

	//writeDebugStreamLine("L - R is %d - %d", leftSpeed + leftMod, rightSpeed + rightMod); //DEBUG: this
}

void resetEncoders() {
	nMotorEncoder[backLeftDrive] = 0;
	nMotorEncoder[backRightDrive] = 0;
}

float encLVal = 0;
float encRVal = 0;

//moves straight
void moveRotations(float rotations, const int negitaveMod, int maxTimeout=3000, int maxPower=70, int minPower=12) {
	//bool isForwards = false;
	//float kp = 0.07;  //new kp
	float kp = 0.22;  //new kp
	bool exitLoop = false;

	float error = 0;

	encLVal = 0;
	encRVal = 0;

	clearTimer(T3);  //start timer

	error = 0;

  float speed = 0;

	//init encoders
	nMotorEncoder[backLeftDrive] = 0;
	nMotorEncoder[backRightDrive] = 0;

	while(exitLoop == false && time1(T3) < maxTimeout) {
    encLVal = abs(nMotorEncoder[backLeftDrive]);
    encRVal = abs(nMotorEncoder[backRightDrive]);

		error = abs(rotations * 360) - encLVal;  //how close to completed.
    speed = error * kp;
    writeDebugStreamLine("speed is %d, error2 is %d", speed, error); //DEBUG: this

    //keep speed between min and max power.
    if(speed < minPower && speed > 0) {
  		speed = minPower;
  	} else if(speed > -minPower && speed < 0) {
      speed = -minPower;
    }

  	if(speed > maxPower) {
  		speed = maxPower;
  	} else if(speed < -maxPower) {
      speed = -maxPower;
    }

		setLeftRightMoveSpeed(speed * negitaveMod, speed * negitaveMod);  //move forwards (also does straightening)

		// check for finish
		if (abs(error) > 5) 	// if robot is within 5 degree wheel rotations and timer flag is off
			clearTimer(T1);			// start a timer

		if (time1(T1) >= 90)	// if the timer is over 90ms and timer flag is true (3 ticks)
			exitLoop = true;	// set boolean to complete while loop

		wait1Msec(20);  //loop speed.
	}

	setLeftRightMoveSpeed(); //turn off motors.

  //reove distance that was supposed to be moved.
	nMotorEncoder[backLeftDrive] = 0;
	nMotorEncoder[backRightDrive] = 0;

	return;
}

void moveStraightGyro(float inches, const int negitaveMod=dir_forwards, int maxTimeout=5000, int maxPower=102, int minPower=17) {
	float disKp = 0.22;  //distance kp.
	float gyroKp = 2.2;

	float error = 0;
	float gyroError = SensorValue[gyro];

	int sideMod = 0;

	clearTimer(T3);  //start timer

  float speed = 0;

	//init encoders
	nMotorEncoder[backLeftDrive] = 0;
	nMotorEncoder[backRightDrive] = 0;

	bool exitLoop = false;
	while(exitLoop == false && time1(T3) < maxTimeout) {
		float encAvgLR = (abs(nMotorEncoder[backLeftDrive]) + abs(nMotorEncoder[backRightDrive])) / 2;

		error = abs(inches / mod_wheel_circumference * 360) - encAvgLR;  //how close to completed.
    speed = error * disKp;

    writeDebugStreamLine("speed is %d, error2 is %d", speed, error); //DEBUG: this

    gyroError -= SensorValue[gyro];
    sideMod = gyroError * gyroKp;

    //keep speed between min and max power.
    if(speed < minPower && speed > 0) {
  		speed = minPower;
  	} else if(speed > -minPower && speed < 0) {
      speed = -minPower;
    }

  	if(speed > maxPower) {
  		speed = maxPower;
  	} else if(speed < -maxPower) {
      speed = -maxPower;
    }

		setLeftRightMoveSpeed((speed * sideMod) * negitaveMod, (speed * -sideMod) * negitaveMod);  //move forwards (also does straightening)

		// check for finish
		if (abs(error) > 5) 	// if robot is within 5 degree wheel rotations and timer flag is off
			clearTimer(T1);			// start a timer

		if (time1(T1) >= 90)	// if the timer is over 90ms and timer flag is true (3 ticks)
			exitLoop = true;	// set boolean to complete while loop

		wait1Msec(20);  //loop speed.
	}

	setLeftRightMoveSpeed(); //turn off motors.

  //remove distance that was supposed to be moved.
	nMotorEncoder[backLeftDrive] = 0;
	nMotorEncoder[backRightDrive] = 0;

	return;
}

void moveInches(float inches, const int negitaveMod=dir_forwards, int maxTimeout=3000) {
	moveRotations(inches / mod_wheel_circumference, negitaveMod);  //converts inches to rotations.
}

//NOT DONE
bool hitLine = false;
task lookForLine {
	//set hitLine to not have been hit.
	hitLine = false;
	while (hitLine == false) {
		//look for the line.

		//if found line hitLine = true;
	}
}

// **GYRO TURN**
// target (in degrees) is added/subtracted from current gyro reading to get a target gyro reading
// run PD loop to turn to target
// checks if target has been reached AND is at target for over 250ms before moving on
void gyroTurn (int turnDirection, int targetDegrees, int maxPower=80, int minPower=23, int timeOut=3000) {
	// initialize PD loop variables
	float kp = 0.22; // TO BE TUNED
	int error = targetDegrees;
	int drivePower = 0;

	clearTimer(T2);

	// finish check variables
	bool atTarget = false;

	// initialize gyro data variables
	int targetReading = SensorValue[gyro];

	// get gyroscope target reading
	if (turnDirection >= 1)
		targetReading += targetDegrees;
	else if (turnDirection <= 0)
		targetReading -= targetDegrees;

	// change kp if target is under 20 degree threshold
	if (targetDegrees < 200) { kp = 0.2; }  //ok?

	// run motors until target is within 1 degree certainty
	while (!atTarget && (time1[T2] < timeOut)) {
		error = targetReading - SensorValue[gyro]; 	// calculate error
		drivePower = error * kp;	// calculate PD loop output  //speed

		writeDebugStreamLine("error -> %d, gyro -> %d", error, SensorValue[gyro]);  //DEBUG: this

		//keep speed between min and max power.
		if(drivePower < minPower && drivePower > 0) {
			drivePower = minPower;
		}
		else if(drivePower > -minPower && drivePower < 0) {
      drivePower = -minPower;
    }

		if(drivePower > maxPower) {
			drivePower = maxPower;
		}
		else if(drivePower < -maxPower) {
    	drivePower = -maxPower;
    }

		//send power to motors. //(also does straightening)
		setLeftRightMoveSpeed(-drivePower, drivePower);

		// check for finish
		if (abs(error) > 8) 	// if robot is within 0.8 degree off target and timer flag is off
			clearTimer(T1);			// start a timer

		if (time1(T1) > 150)	// if the timer is over 200ms and timer flag is true
			atTarget = true;	// set boolean to complete while loop

		wait1Msec(20);  //let motors update.
	}

	setLeftRightMoveSpeed();  //reset motors.

	// reset kp  wtf is this?  TODO: delete?
	kp = 0.22;

	resetEncoders();
  return; //I think I need this.
}

//NOT DONE
//value is in inches.
//precision is for how accurate the value is going to be.  More accurate -> longer time to get value.
float getRFDistance (int precision=5, int pollingTime=40) {
	float sumDistances = 0;  //holds all of the distances from the rangefinder.

	for (int i = 0; i < precision; i++) {
		sumDistances += SensorValue[urfOut];  //fetch!  Good boy!

		wait1Msec(pollingTime);  //longer pollingTime means longer to get values.  Too quick and cortex cant keep up / gives same number.  Sensor polling is 3ms.
	}

	return sumDistances / precision;
}

///the real autonomous command.
void runAutoSkills() {

  ///So far code moves robot to pick up and place two goals
  ///this gives 30 pts.
  ///

	/*Drop goal arm & mini goal arm + Drive into G1*/
	armParam = down; startTask(autoMoveGoalArms);
  miniArmParam = down; startTask(autoMoveMiniGoalArms);
	moveInches(42, dir_forwards);

  /*Large goal up + Drive into G2*/
  armParam = up; startTask(autoMoveGoalArms);
  moveInches(36, dir_forwards);

  /*Mini goal up + Drive into P1*/
  miniArmParam = up; startTask(autoMoveMiniGoalArms);
  moveInches(31.2, dir_forwards);

  /*Rotate 90 deg left*/
  gyroTurn(dir_left, 90 * mod_degrees);

  /*Drive to P2*/
  moveInches(16.56, dir_forwards);

  /*Rotate 90 deg right*/
  gyroTurn(dir_right, 90 * mod_degrees);

  /*Drive to 20pt goal*/
  moveInches(29.76, dir_forwards);

  /*Mini goal down*/
  miniArmParam = down; startTask(autoMoveMiniGoalArms);
  waitUntil(miniArmParam == completed);

  /*Pull back into 10pt goal*/
  moveInches(12.36, dir_backwards);

  /*Large goal down*/
  armParam = down; startTask(autoMoveGoalArms);
  waitUntil(armParam == completed);

  /*Pull back to P2*/
  moveInches(17.4, dir_backwards);

  /*Ore wo dare da to omotte yagaru?!*/
}

void runAutoComp() {

  ///So far code gets 7/9 pts, gets one goal in 5 pts and parks
  /// TODO: do arm thing.

	/*Drop goal arm & mini goal arm + Drive into G5*/
	armParam = down; startTask(autoMoveGoalArms);
  miniArmParam = down; startTask(autoMoveMiniGoalArms);
	moveInches(57.6, dir_forwards);

  /*Large goal up*/
  armParam = up; startTask(autoMoveGoalArms);
  waitUntil(armParam == completed);

  /*Rotate 180 deg left*/
  gyroTurn(dir_left, 180 * mod_degrees);

  /*Drive into 5pt goal*/
  moveInches(50.4, dir_forwards);

  /*Large goal down*/
  armParam = down; startTask(autoMoveGoalArms);
  waitUntil(armParam == completed);

  /*Pull back and park*/
  moveInches(50.4, dir_backwards);

  /*Ore wo dare da to omotte yagaru?!*/
}

void pre_auton() {
	gyroInit();
  string startgame = "fun";  //Do not remove or script doesn't work anymore, I dunno why.
}

task autonomous	{
	runAutoComp();  //this calls the autonomous script.
}

float armError = 0;
int armSpeed = 50;
int degToMove = -100;
float armKp = 1.5;

bool clawClosed = false;

bool tempLock = false;
bool isHoldingClaw = false;
bool isGoalArmMovingDown = false;
bool inDropPos = false;
bool moveArmToDrop = false;

task coneDrop { wait1Msec(500); moveArmToDrop = false; }

task usercontrol {
	writeDebugStreamLine("***************Start************");
	writeDebugStreamLine("***************Start************");
	writeDebugStreamLine("***************Start************");
	writeDebugStreamLine("***************Start************");

	writeDebugStreamLine("Done");
	inTeleop = true;
  resetMoveMod(); //just no encs during user k?
	while(true) {
		/*Goal Arm*/
		if(vexRT[Btn8R] == 1)	{
			isGoalArmMovingDown = true;
		} else if (vexRT[Btn8D] == 1 ) {
			isGoalArmMovingDown = false;
		}

		if(isGoalArmMovingDown == true && SensorValue[handsDown] == 0) {
			motor[goalHands] = -127;
		} else if (isGoalArmMovingDown == false && SensorValue[handsUp] == 0){
			motor[goalHands] = 127;
		} else {
			motor[goalHands] = 0;
		}

		/*Cone Arm*/
		if(vexRT[Btn5U] == 1)	{
			motor[coneArms] = 100;
		} else if (vexRT[Btn5D] == 1) {
			motor[coneArms] = -100;
		} else {
			motor[coneArms] = 0;
		}

		/*Move Arm to Drop Pos*/
		if(vexRT[Btn8U] == 1) {
			if(inDropPos == false) { moveArmToDrop = true; }
			inDropPos = true;
		} else {
			inDropPos = false;
		}

		/*Claws*/
		if(vexRT[Btn6U] == 1)	{
			isHoldingClaw = false;
			motor[claw] = 127;

			if(clawClosed == false) {  //stop arm movement is called once when the button is first pressed.
				if(moveArmToDrop == true) { startTask(coneDrop); }
			}
			clawClosed = true;

		} else if (vexRT[Btn6D] == 1) {
			isHoldingClaw = true;
			motor[claw] = -127;
		} else {
			clawClosed = false;
			//keeps pressure on the cone when picked up.
			if(isHoldingClaw == true) {
				motor[claw] = -10;  //TODO: change value down or up if pressure is wrong.
			} else {
				motor[claw] = 0;
			}
		}

		if(vexRT[Btn7L] == 1)	{
			motor[pushGoalHand] = 127;
		} else if(vexRT[Btn7D] == 1) {
			motor[pushGoalHand] = -127;
		} else {
			motor[pushGoalHand] = 0;
		}

		/*Tank Drive*/
		setLeftRightMoveSpeed(vexRT[Ch3], vexRT[Ch2]);

		/*Auto Move Arm To Drop Pos*/
		if(moveArmToDrop == true) {
			armError = degToMove + SensorValue[encArm];  //finds distance left to go
			armSpeed = armError * armKp;

			setConePickUpSpeed(armSpeed);

			//if(armError < 0.5 && armError > 0.5) {  //If within 0.5 degrees of pos.
			//}
		}

		writeDebugStreamLine("gyro is %d", SensorValue[gyro]);  //DEBUG: this

		//let everything update
		wait1Msec(20);  //TODO: remove?
	}
}
