#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    accelX,         sensorAccelerometer)
#pragma config(Sensor, in3,    accelY,         sensorAccelerometer)
#pragma config(Sensor, dgtl1,  encArm,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  handsDown,      sensorTouch)
#pragma config(Sensor, dgtl6,  handsUp,        sensorTouch)
#pragma config(Sensor, dgtl8,  urfOut,         sensorSONAR_inch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           pushGoalHand,  tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           claw,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           coneArmsOuter, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontLeftDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           frontRightDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           coneArmsInner, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           backLeftDrive, tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port8,           backRightDrive, tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port9,           goalHandLeft,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          goalHandRight, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//warning code is slightly agressive.

/*Compo Init*/
#pragma platform(VEX);

#pragma competitionControl(Competition);
#pragma autonomousDuration(9000);
#pragma userControlDuration(9000);

#include "Vex_Competition_Includes.c" //backcode no modify pls.

/*Other Scripts*/
//#include "64008Z_auto_v2.c" //autonomous code.
const string down = "down";
const string up = "up";

bool inTeleop = false;

float currentTick = 0;

//

int roundToInt(float f) {  //rounds value to int.
  if(f>0)
  	return (int)(f + 0.5);
  else
  	return (int)(f - 0.5);
}

///initialize the gyroscope
void gyroInit() {
	writeDebugStreamLine("Gyro Reset.");
	SensorType[gyro] = sensorNone;
	wait1Msec(1000);

	writeDebugStreamLine("Gyro Assign..");
	SensorType[gyro] = sensorGyro;
	wait1Msec(2000);

	writeDebugStreamLine("Gyro Setup...");
	SensorScale[gyro] = 280;  // try this
	SensorValue[gyro] = 0;
	SensorFullCount[gyro] = 3600;  //not working, gyro is auto set to 3600.
}

//TODO: TEST THIS.
///direction = up(const) for up move and down(const) for down move.
void autoMoveGoalArms(const string direction) {
	if(direction == up) {
		motor[goalHandLeft] = 127;
		motor[goalHandRight] = 127;
    waitUntil(SensorValue[handsUp] == 1);
	}
	else {
		motor[goalHandLeft] = -127;
		motor[goalHandRight] = -127;
    waitUntil(SensorValue[handsDown] == 1);
	}

	motor[goalHandLeft] = 0;
	motor[goalHandRight] = 0;
}

///sets cone pickup speed.  Empty is not moving.
void setConePickUpSpeed (int val=0) {
	motor[coneArmsOuter] = val;
	motor[coneArmsInner] = val;
}

float kp = 0.9;

float errorVal = 0;

int leftMod = 0;
int rightMod = 0;
void straightenMotors() {
  //set offset value, if 0 both sides are moving at same speed.  use abs value for both motors, pretending both sides going forwards.
  errorVal = (abs(nMotorEncoder[backLeftDrive]) - abs(nMotorEncoder[backRightDrive]));

  //update both modifiers.
  rightMod = (errorVal * kp);
  leftMod = -rightMod;

  //writeDebugStreamLine("The motor modifier of (mod = error[%d] * kp[%d]) is +[%d / 127] motor speed -> at tick %d", errorVal, kp, leftMod, currentTick);  //DEBUG: this
  //writeDebugStreamLine("The error of (L - R) is %d degrees -> at tick %d", errorVal, currentTick);  //DEBUG: this
}

void resetMoveMod () { leftMod = 0; rightMod = 0; }  //small func.

//*VERY IMPORTANT*: THIS MUST BE CALLED FOR STRAIGHTENING TO OCCUR.
//sets the speed of the left and right sides of the drive.  Empty is not moving.
void setLeftRightMoveSpeed(int leftSpeed=0, int rightSpeed=0) {
  if (inTeleop == false) {
    straightenMotors();
  }  //make sure not to straighten motors while in teleop.  Don't fuck with Victor.

	//left side, add positive mod.
	motor[frontLeftDrive] = abs(leftSpeed) + leftMod;
  motor[backLeftDrive] = abs(leftSpeed) + leftMod;
  //if negitave, make negitave.
  if(leftSpeed < 0) {
    motor[frontLeftDrive] *= -1;
    motor[backLeftDrive] *= -1;
  }

	//right side, add positive mod.
	motor[frontRightDrive] = abs(rightSpeed) + rightMod;
	motor[backRightDrive] = abs(rightSpeed) + rightMod;
  //if negitave, make negitave.
  if(rightSpeed < 0) {
    motor[frontRightDrive] *= -1;
    motor[backRightDrive] *= -1;
  }

	//writeDebugStreamLine("L - R is %d - %d", leftSpeed + leftMod, rightSpeed + rightMod); //DEBUG: this
}

float encLVal = 0;
float encRVal = 0;

float error = 0;
//moves straight
void moveRotations(float rotations, int negitaveMod=1, int maxPower=92, int minPower=27) {
	//bool isForwards = false;
	float kp = 0.25;  //new kp
	bool exitLoop = false;

	encLVal = 0;
	encRVal = 0;

	error = 0;

  float speed = 80;

	//init encoders
	nMotorEncoder[backLeftDrive] = 0;
	nMotorEncoder[backRightDrive] = 0;

	while(exitLoop == false) {
    encLVal = nMotorEncoder[backLeftDrive];
    encRVal = nMotorEncoder[backRightDrive];

		error = (abs(rotations) * 360) - encLVal;
    speed = error * kp;

    //keep speed between min and max power.
    if(speed < minPower && speed > 0) {
  		speed = minPower;
  	} else if(speed > -minPower && speed < 0) {
      speed = -minPower;
    }

  	if(speed > maxPower) {
  		speed = maxPower;
  	} else if(speed < -maxPower) {
      speed = -maxPower;
    }

		setLeftRightMoveSpeed(speed * negitaveMod, speed * negitaveMod);  //move forwards (also does straightening)

		if (abs(encLVal) >= abs(rotations) * 360) { //case: loop is done motor is at (or past) correct position.
			exitLoop = true; //main loop exit.
		}

    currentTick++;  //DEBUG: to find ticks
		wait1Msec(40);
	}

	setLeftRightMoveSpeed(); //turn off motors.

  //reset encoders, just incase.
	nMotorEncoder[backLeftDrive] = 0;
	nMotorEncoder[backRightDrive] = 0;

	return;
}

float wheelRadius = 4 * 3.1415926535897932; //in inches.  (that's right, I memorized that many characters...)
void moveInches(float value, int negitaveMod=1) {
	moveRotations(value / wheelRadius, negitaveMod);  //converts inches to rotations.
}

bool hitLine = false;
task lookForLine {
	//set hitLine to not have been hit.
	hitLine = false;
	while (hitLine == false) {
		//look for the line.

		//if found line hitLine = true;
	}
}

// **GYRO TURN**
// target (in degrees) is added/subtracted from current gyro reading to get a target gyro reading
// run PD loop to turn to target
// checks if target has been reached AND is at target for over 250ms before moving on
void gyroTurn (int turnDirection, int targetDegrees, bool isDirectValue=false, int maxPower=92, int minPower=27, int timeOut=3000) {
	// initialize PD loop variables
	float kp = 0.26; // TO BE TUNED
	int error = targetDegrees;
	int drivePower = 0;

	clearTimer(T2);

	// finish check variables
	bool atTarget = false;

	// initialize gyro data variables
	int targetReading = SensorValue[gyro];

	// get gyroscope target reading
	if (turnDirection >= 1)
		targetReading += targetDegrees;
	else if (turnDirection <= 0)
		targetReading -= targetDegrees;

	// change kp if target is under 20 degree threshold
	if (targetDegrees < 200) { kp = 0.2; }  //ok?

	// run motors until target is within 1 degree certainty
	while (!atTarget && (time1[T2] < timeOut)) {
		error = targetReading - SensorValue[gyro]; 	// calculate error
		drivePower = error * kp;	// calculate PD loop output  //speed

		writeDebugStreamLine("error -> %d, gyro -> %d", error, SensorValue[gyro]);  //DEBUG: this

		//keep speed between min and max power.
		if(drivePower < minPower && drivePower > 0) {
			drivePower = minPower;
		}
		else if(drivePower > -minPower && drivePower < 0) {
      drivePower = -minPower;
    }

		if(drivePower > maxPower) {
			drivePower = maxPower;
		}
		else if(drivePower < -maxPower) {
    	drivePower = -maxPower;
    }

		//send power to motors. //(also does straightening)
		setLeftRightMoveSpeed(-drivePower, drivePower);

		// check for finish
		if (abs(error) > 10) 	// if robot is within 1 degree off target and timer flag is off
			clearTimer(T1);			// start a timer

		if (time1(T1) > 200)	// if the timer is over 200ms and timer flag is true
			atTarget = true;	// set boolean to complete while loop
	}

	setLeftRightMoveSpeed();  //reset motors.

	// reset kp  wtf is this?  TODO: delete?
	kp = 0.26;

  return; //I think I need this.
}

//value is in inches.
//precision is for how accurate the value is going to be.  More accurate -> longer time to get value.
float getRFDistance (int precision=5, int pollingTime=40) {
	float sumDistances = 0;  //holds all of the distances from the rangefinder.

	for (int i = 0; i < precision; i++) {
		sumDistances += SensorValue[urfOut];  //fetch!  Good boy!

		wait1Msec(pollingTime);  //longer pollingTime means longer to get values.  Too quick and cortex cant keep up / gives same number.  Sensor polling is 3ms.
	}

	return sumDistances / precision;
}

///the real autonomous command.
void runAuto() {
	/*Drop Goal Arms*/
	autoMoveGoalArms(down);

	/*Move Forwards One Rotation*/
	moveRotations(1, 100);

	/**/
}

void pre_auton() {
	gyroInit();
  string startgame = "fun";  //Do not remove or script doesn't work anymore, I dunno why.
}

task autonomous	{
	//DEBUG: just test code now.

	gyroTurn(-1, 9000);


	/*moveRotations(6);
	wait1Msec(2000);

	moveRotations(6, -1);
	wait1Msec(2000);

	moveRotations(6);
	wait1Msec(2000);

	moveRotations(6, -1);
	wait1Msec(2000);*/

	//runAuto();  //this calls the autonomous script.
}

float armError = 0;
int armSpeed = 50;
int degToMove = 170;

bool tempLock = false;
bool isHoldingClaw = false;
bool isGoalArmMovingDown = false;
bool inDropPos = false;
bool moveArmToDrop = false;
task usercontrol {
  inTeleop = true;

	writeDebugStreamLine("***************Start************");
	writeDebugStreamLine("***************Start************");
	writeDebugStreamLine("***************Start************");
	writeDebugStreamLine("***************Start************");
	gyroInit();
	/*moveRotations(6);
	wait1Msec(1000);

	moveRotations(6, -1);
	wait1Msec(1000);

	moveRotations(6);
	wait1Msec(1000);

	moveRotations(6, -1);
	wait1Msec(1000);*/

	//gyroTurn(1, 90);

	gyroTurn(-1, 2780);
	wait1Msec(1000);

	gyroTurn(1, 2780);
	wait1Msec(1000);

	writeDebugStreamLine("Done");

  resetMoveMod(); //reset any mod before controller period so code doesn't fuck with victor.  Dont fuck with victor guys...
	while(true) //TODO: set to true so loop goes.
	{
		/*Goal Arm*/
		if(vexRT[Btn8R] == 1)	{
			isGoalArmMovingDown = true;
		}
		else if (vexRT[Btn8D] == 1 ) {
			isGoalArmMovingDown = false;
		}

		if(isGoalArmMovingDown == true && SensorValue[handsDown] == 0) {
			motor[goalHandLeft] = -127;
			motor[goalHandRight] = -127;
		}
		else if (isGoalArmMovingDown == false && SensorValue[handsUp] == 0){
			motor[goalHandLeft] = 127;
			motor[goalHandRight] = 127;
		}
		else {
			motor[goalHandLeft] = 0;
			motor[goalHandRight] = 0;
		}

		/*Cone Arm*/
		if(vexRT[Btn5U] == 1)	{
			setConePickUpSpeed(120);
		}
		else if (vexRT[Btn5D] == 1) {
			setConePickUpSpeed(-120);
		}
		else {
			setConePickUpSpeed();
		}

		/*Move Arm to Drop Pos*/
		if(vexRT[Btn8U] == 1) {
			if(inDropPos == false) { moveArmToDrop = true; }
			inDropPos = true;
		}
		else {
			inDropPos = false;
		}

		/*Claws*/
		if(vexRT[Btn6U] == 1)	{
			motor[claw] = 127;
			isHoldingClaw = false;
		}
		else if (vexRT[Btn6D] == 1) {
			motor[claw] = -127;
			isHoldingClaw = true;
		}
		else {
			//keeps pressure on the cone when picked up.
			if(isHoldingClaw == true) {
				motor[claw] = -10;  //TODO: change value down or up if pressure is wrong.
			}
			else {
				motor[claw] = 10;
			}
		}

		if(vexRT[Btn7U] == 1)	{
			setLeftRightMoveSpeed(127, 127);
		}

		if(vexRT[Btn7L] == 1)	{
			motor[pushGoalHand] = 127;
		}
		else if(vexRT[Btn7D] == 1) {
			motor[pushGoalHand] = -127;
		}
		else {
			motor[pushGoalHand] = 0;
		}

		/*Tank Drive*/
		setLeftRightMoveSpeed(vexRT[Ch3], vexRT[Ch2]);

		/*Auto Move Arm To Drop Pos*/
		float armKp = 2.2;
		if(moveArmToDrop == true) {
			armError = degToMove - SensorValue[encArm];  //finds distance left to go
			armSpeed = armError * armKp;

			setConePickUpSpeed(armSpeed);

			if(armError < 0.5 && armError > 0.5) {  //If within 0.5 degrees of pos.
				while (moveArmToDrop == true) {
					//TODO: drop cone?

					moveArmToDrop = false;
				}

			}

		}

	}
}
